name = "DiffusiveShockAccelerationModels"
uuid = "66fc4661-a670-4cc2-b407-bfd81989e880"
authors = ["Ludwig Böss"]
version = "0.1.1"

[deps]
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
PrecompileTools = "1"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
